/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.shichuangnet.heero.sortvisual.linklist.visualizer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import static org.shichuangnet.heero.sortvisual.linklist.visualizer.LinklistVisualizer.SHUFFLEANIM;
import static org.shichuangnet.heero.sortvisual.linklist.visualizer.LinklistVisualizer.SHUFFLEMETHOD;
import static org.shichuangnet.heero.sortvisual.linklist.visualizer.LinklistVisualizer.SLEEPRATIO;

/**
 *
 * @author JOJO
 * 设置界面，有 调节速度、启用复位动画、选择打乱方式
 * 该窗口启用了 setFocusableWindowState(false)，用于隐藏该窗口在状态栏底部的状态栏
 * 因此失去了焦点，textFiled组件无法在此窗口获得焦点
 */
public class SettingView extends javax.swing.JFrame implements IView {
    
    JFrame f;
    boolean _SHUFFLEANIM = SHUFFLEANIM;
    boolean _SHUFFLEMETHOD = SHUFFLEMETHOD;
    
    public SettingView(JFrame f) {
        this.f = f;
        initComponents();
        setLocation(f.getX()+(f.getWidth()-getWidth())/2, f.getY()+(f.getHeight()-getHeight())/2);
        setVisible(true);
        
        if (SHUFFLEANIM) {
            shuffAnimRadioBtn_1.setSelected(true);
        } else
            shuffAnimRadioBtn_2.setSelected(true);
        if (SHUFFLEMETHOD) {
            shuffMethodRadioBtn_1.setSelected(true);
        } else
            shuffMethodRadioBtn_2.setSelected(true);
        animSpeedSlider.setValue((int) (SLEEPRATIO*50));
    }
    
    @Override
    public void reposition() {
        setLocation(f.getX()+(f.getWidth()-getWidth())/2, f.getY()+(f.getHeight()-getHeight())/2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        jPanel1 = new JPanel();
        okButton = new JButton();
        jLabel1 = new JLabel();
        jSeparator1 = new JSeparator();
        shuffMethodRadioBtn_1 = new JRadioButton();
        shuffMethodRadioBtn_2 = new JRadioButton();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        shuffAnimRadioBtn_1 = new JRadioButton();
        shuffAnimRadioBtn_2 = new JRadioButton();
        animSpeedSlider = new JSlider();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting");
        setAlwaysOnTop(true);
        setFocusableWindowState(false);
        setUndecorated(true);
        setResizable(false);

        okButton.setText("确定");
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("设置");

        buttonGroup1.add(shuffMethodRadioBtn_1);
        shuffMethodRadioBtn_1.setSelected(true);
        shuffMethodRadioBtn_1.setText("随机");
        shuffMethodRadioBtn_1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                shuffMethodRadioBtn_1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(shuffMethodRadioBtn_2);
        shuffMethodRadioBtn_2.setText("逆置");
        shuffMethodRadioBtn_2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                shuffMethodRadioBtn_2ActionPerformed(evt);
            }
        });

        jLabel2.setText("动画速度");

        jLabel3.setText("打乱方式");

        jLabel4.setText("打乱动画");

        buttonGroup2.add(shuffAnimRadioBtn_1);
        shuffAnimRadioBtn_1.setSelected(true);
        shuffAnimRadioBtn_1.setText("开启");
        shuffAnimRadioBtn_1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                shuffAnimRadioBtn_1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(shuffAnimRadioBtn_2);
        shuffAnimRadioBtn_2.setText("关闭");
        shuffAnimRadioBtn_2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                shuffAnimRadioBtn_2ActionPerformed(evt);
            }
        });

        animSpeedSlider.setMajorTickSpacing(20);
        animSpeedSlider.setMinorTickSpacing(20);
        animSpeedSlider.setPaintTicks(true);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(okButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shuffMethodRadioBtn_1))
                            .addComponent(shuffAnimRadioBtn_1))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(shuffAnimRadioBtn_2)
                            .addComponent(shuffMethodRadioBtn_2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(animSpeedSlider, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
                    .addComponent(animSpeedSlider, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(shuffMethodRadioBtn_2)
                    .addComponent(shuffMethodRadioBtn_1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(shuffAnimRadioBtn_1)
                    .addComponent(shuffAnimRadioBtn_2))
                .addGap(28, 28, 28)
                .addComponent(okButton)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        SHUFFLEANIM = _SHUFFLEANIM;  //  是否需要打乱动画
        SHUFFLEMETHOD = _SHUFFLEMETHOD;  //  打乱方式
        
        double sleepRatio = ((double)animSpeedSlider.getValue())/50;
        if (sleepRatio <= 0) {
            SLEEPRATIO = 0.1;
        } else
            SLEEPRATIO = sleepRatio;
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void shuffMethodRadioBtn_1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_shuffMethodRadioBtn_1ActionPerformed
        _SHUFFLEMETHOD = true;
    }//GEN-LAST:event_shuffMethodRadioBtn_1ActionPerformed

    private void shuffAnimRadioBtn_1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_shuffAnimRadioBtn_1ActionPerformed
        _SHUFFLEANIM = true;
    }//GEN-LAST:event_shuffAnimRadioBtn_1ActionPerformed

    private void shuffAnimRadioBtn_2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_shuffAnimRadioBtn_2ActionPerformed
        _SHUFFLEANIM = false;
    }//GEN-LAST:event_shuffAnimRadioBtn_2ActionPerformed

    private void shuffMethodRadioBtn_2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_shuffMethodRadioBtn_2ActionPerformed
        _SHUFFLEMETHOD = false;
    }//GEN-LAST:event_shuffMethodRadioBtn_2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JSlider animSpeedSlider;
    ButtonGroup buttonGroup1;
    ButtonGroup buttonGroup2;
    JLabel jLabel1;
    JLabel jLabel2;
    JLabel jLabel3;
    JLabel jLabel4;
    JPanel jPanel1;
    JSeparator jSeparator1;
    JButton okButton;
    JRadioButton shuffAnimRadioBtn_1;
    JRadioButton shuffAnimRadioBtn_2;
    JRadioButton shuffMethodRadioBtn_1;
    JRadioButton shuffMethodRadioBtn_2;
    // End of variables declaration//GEN-END:variables

}
